#!/usr/bin/env perl
# Embeds a binary file as a C byte array, so it can be compiled directly
# into the binary instead of looked up by path at runtime (fragile under
# this project's staged/DESTDIR install model -- see font-rendering plan).
use strict;
use warnings;

my ( $in, $out_c, $out_h, $sym ) = @ARGV;
die "usage: bin2c.pl <input> <out.c> <out.h> <symbol>\n"
    unless defined $in && defined $out_c && defined $out_h && defined $sym;

open( my $fh, '<:raw', $in ) or die "open $in: $!";
local $/;
my $data = <$fh>;
close $fh;

my @bytes = unpack( 'C*', $data );
my $len   = scalar @bytes;

open( my $c, '>', $out_c ) or die "open $out_c: $!";
print $c "/* Generated by font_atlas/bin2c.pl from $in. Do not edit. */\n";
print $c "#include \"${sym}.h\"\n";
print $c "const unsigned char ${sym}\[\] = {\n";
for ( my $i = 0 ; $i < @bytes ; $i += 16 )
{
    my $last = ( $i + 15 < $#bytes ) ? $i + 15 : $#bytes;
    print $c join( ',', map { sprintf( '0x%02x', $_ ) } @bytes[ $i .. $last ] ), ",\n";
}
print $c "};\n";
print $c "const unsigned int ${sym}_len = ${len}u;\n";
close $c;

my $guard = uc($sym) . "_H";
open( my $h, '>', $out_h ) or die "open $out_h: $!";
print $h "#ifndef $guard\n#define $guard\n";
print $h "extern const unsigned char ${sym}\[\];\n";
print $h "extern const unsigned int ${sym}_len;\n";
print $h "#endif\n";
close $h;
